# 1-2 PyTorch 數值型態與基本運算

##  PyTorch 數值型態

In [1]:
import torch
tmp_tensor = torch.tensor([1])
float_32 = torch.FloatTensor([1.01]) # 32 bits
float_64 = torch.DoubleTensor([1.01]) # 64 bits
int_32 = torch.IntTensor([1]) # 32 bits
int_64 = torch.LongTensor([1]) # 64 bits

In [2]:
names = ['float_32', 'float_64', 'int_32', 'int_64']
for i, tmp1 in enumerate([float_32, float_64, int_32, int_64]):
    for j, tmp2 in enumerate([float_32, float_64, int_32, int_64]):
        print('{} + {}:\t{}'.format(names[i], names[j], (tmp1+tmp2).dtype))
        print('{} * {}:\t{}'.format(names[i], names[j], (tmp1*tmp2).dtype))
        print('{} / {}:\t{}'.format(names[i], names[j], (tmp1/tmp2).dtype))

float_32 + float_32:	torch.float32
float_32 * float_32:	torch.float32
float_32 / float_32:	torch.float32
float_32 + float_64:	torch.float64
float_32 * float_64:	torch.float64
float_32 / float_64:	torch.float64
float_32 + int_32:	torch.float32
float_32 * int_32:	torch.float32
float_32 / int_32:	torch.float32
float_32 + int_64:	torch.float32
float_32 * int_64:	torch.float32
float_32 / int_64:	torch.float32
float_64 + float_32:	torch.float64
float_64 * float_32:	torch.float64
float_64 / float_32:	torch.float64
float_64 + float_64:	torch.float64
float_64 * float_64:	torch.float64
float_64 / float_64:	torch.float64
float_64 + int_32:	torch.float64
float_64 * int_32:	torch.float64
float_64 / int_32:	torch.float64
float_64 + int_64:	torch.float64
float_64 * int_64:	torch.float64
float_64 / int_64:	torch.float64
int_32 + float_32:	torch.float32
int_32 * float_32:	torch.float32
int_32 / float_32:	torch.float32
int_32 + float_64:	torch.float64
int_32 * float_64:	torch.float64
int_32 / float_64:	

當你的Tensor是**參數**型態，也就是可微分求解的，這時候資料型態就不可以任意改變。<br>
一般Torch模型參數預設是浮點數Float32。<br>
Numpy預設的浮點數Double (Float64)，所以在使用上要特別注意這點，因為我們常常會把numpy的array轉成Torch的Tensor。<br>


In [3]:
import torch
import torchvision
mobilenet_v2 = torchvision.models.mobilenet_v2(pretrained=True)
mobilenet_v2.eval() 
dummy_input = torch.randn(1, 3, 224, 224)
print(dummy_input.dtype)
tmp = mobilenet_v2(dummy_input)
print(tmp.dtype)
print('---------')

torch.float32
torch.float32
---------


如果我們沒有注意到輸入的資料格式，直接把numpy的array轉成torch tensor輸入到模型內。

In [5]:
import cv2
import numpy as np
img = cv2.imread('example.png')
img = cv2.resize(img, (224,224))
img = np.array(img)/255
print(img.shape)
print(img.dtype)
img = torch.tensor(img)
img = img.permute(2, 0, 1)
print(img.shape)
print(img.dtype)
img=img.unsqueeze(0)
print(img.shape)
print(img.dtype)


(224, 224, 3)
float64
torch.Size([3, 224, 224])
torch.float64
torch.Size([1, 3, 224, 224])
torch.float64


In [6]:
tmp = mobilenet_v2(img)

RuntimeError: expected scalar type Double but found Float

避免這類型的出錯，盡量在numpy array或是image型態轉成torch tensor時候，就指定他是```torch.FloatTensor```。

In [7]:
import cv2
import numpy as np
img = cv2.imread('example.png')
img = cv2.resize(img, (224,224))
img = np.array(img)/255

img = torch.FloatTensor(img)

img = img.permute(2, 0, 1)
img=img.unsqueeze(0)
tmp = mobilenet_v2(img)
print(tmp.shape)

torch.Size([1, 1000])


## PyTorch基本運算


## Numpy-Like Implementation 

In [8]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[2,2,2],
              [3,3,3]])
c = np.array([[1,2],
              [3,4],
              [5,6]])
print('元素點對點相乘(方法1:np.multiply(a,b)):\\\
        \n{}'.format(np.multiply(a,b)))
print('元素點對點相乘(方法2:a*b):\\\
        \n{}'.format(a*b))
print('矩陣相乘(方法1: np.dot(a,c)):\\\
        \n{}'.format(np.dot(a,c)))
print('矩陣相乘(方法2: a.dot(c)):\\\
        \n{}'.format(a.dot(c)))
print('矩陣相乘(方法3: np.matmul(a,c)):\\\
        \n{}'.format(np.matmul(a,c)))

元素點對點相乘(方法1:np.multiply(a,b)):\        
[[ 2  4  6]
 [12 15 18]]
元素點對點相乘(方法2:a*b):\        
[[ 2  4  6]
 [12 15 18]]
矩陣相乘(方法1: np.dot(a,c)):\        
[[22 28]
 [49 64]]
矩陣相乘(方法2: a.dot(c)):\        
[[22 28]
 [49 64]]
矩陣相乘(方法3: np.matmul(a,c)):\        
[[22 28]
 [49 64]]


In [9]:
import torch
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([[2,2,2],
                  [3,3,3]])
c = torch.tensor([[1,2],
                  [3,4],
                  [5,6]])
print('元素點對點相乘(a*b):\\\
        \n{}'.format(a*b))
print('矩陣相乘(方法1: torch.mm(a,c)):\\\
        \n{}'.format( torch.mm(a,c)))
print('矩陣相乘(方法2: torch.matmul(a,c)):\\\
        \n{}'.format( torch.matmul(a,c)))
print('矩陣相乘(方法3: a.matmul(c)):\\\
        \n{}'.format( a.mm(c)))


元素點對點相乘(a*b):\        
tensor([[ 2,  4,  6],
        [12, 15, 18]])
矩陣相乘(方法1: torch.mm(a,c)):\        
tensor([[22, 28],
        [49, 64]])
矩陣相乘(方法2: torch.matmul(a,c)):\        
tensor([[22, 28],
        [49, 64]])
矩陣相乘(方法3: a.matmul(c)):\        
tensor([[22, 28],
        [49, 64]])


看起來```torch.matmul```和```torch.mm```都是進行矩陣內積運算，那```torch.matmul```和```torch.mm```有沒有什麼差異?

```torch.mm```就是一般我們高中數學學的矩陣相乘，```torch.mm(a,b)```的情況，矩陣/向量$a$要能跟矩陣/向量$b$對上<br>
$$a\in R^{(m\times n)}, b\in R^{(n\times k)}，torch.mm(a,b)\in R^{(m\times k)}$$

```torch.matmul```: 除了一般的矩陣內積運算外，他可以達到Python內建很奇怪的運算，叫做broadcasted運算，當兩個tensor的dimension是broadcasted，使用它時候會很有趣。<br>
假設tensor a: $(i\times 1\times n\times m)$ 和 tnesor b: $(k\times m\times p)$<br>
torch.matmul(a,b) = $(i\times k\times n\times p)$

### Torch broadcasted運算

In [10]:
a = torch.tensor([[[2,2,2],
                   [3,3,3]]])
print('a: {}'.format(a.shape))
b = torch.tensor([
    [[[1,1],
      [1,1],
      [1,1]]],
    [[[2,2],
      [2,2],
      [2,2]]],
    [[[3,3],
      [3,3],
      [3,3]]]
])      
print('b: {}'.format(b.shape))
c=torch.matmul(a,b)
print('a * b: {}'.format(c.shape))

m=torch.zeros((3,1,2,2))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j,i,:,:] = torch.mm(a[i,:,:], b[j,0,:,:])
print(((c-m)**2).sum())    


# a = shape[2,4] -> [1,2,4]
# b = shape[2,10] ->[2,1,10]
# B=np.array(4,10)
# for i in range(4):
#     for j in range(10):
#         if j>i:
#             B[i,j] = dist(a[:,i], b[:,j])
            

a: torch.Size([1, 2, 3])
b: torch.Size([3, 1, 3, 2])
a * b: torch.Size([3, 1, 2, 2])
tensor(0.)


## Numpy broadcasted運算

In [11]:
a = np.array([[[2,2,2],
               [3,3,3]]])
print('a: {}'.format(a.shape))
b = np.array([
    [[[1,1],
      [1,1],
      [1,1]]],
    [[[2,2],
      [2,2],
      [2,2]]],
    [[[3,3],
      [3,3],
      [3,3]]]
])      
print('b: {}'.format(b.shape))
c=np.matmul(a,b)
print('a * b: {}'.format(c.shape))

m=np.zeros((3,1,2,2))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j,i,:,:] = np.matmul(a[i,:,:], b[j,0,:,:])
print(((c-m)**2).sum())    

a: (1, 2, 3)
b: (3, 1, 3, 2)
a * b: (3, 1, 2, 2)
0.0


### 利用Python的broadcasted運算特性可以節省for loop的時間。

In [12]:
import time
a=torch.rand((100,5,10))
b=torch.rand((200,1,10,20))
print('a: {}'.format(a.shape))
print('b: {}'.format(b.shape))
st= time.time()
c=torch.matmul(a,b)
print('a * b: {}'.format(c.shape))
print('計算時間:{}'.format(time.time()-st))

st= time.time()
m=torch.zeros((200,100,5,20))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j,i,:,:] = torch.mm(a[i,:,:], b[j,0,:,:])
print('計算時間:{}'.format(time.time()-st))
print((c-m).abs().sum()) 



a: torch.Size([100, 5, 10])
b: torch.Size([200, 1, 10, 20])
a * b: torch.Size([200, 100, 5, 20])
計算時間:0.03949236869812012
計算時間:1.445796012878418
tensor(0.)


In [13]:
import time
a=np.random.rand(100,5,10)
b=np.random.rand(200,1,10,20)
print('a: {}'.format(a.shape))
print('b: {}'.format(b.shape))
st= time.time()
c=np.matmul(a,b)
print('a * b: {}'.format(c.shape))
print('計算時間:{}'.format(time.time()-st))

st= time.time()
m=np.zeros((200,100,5,20))
for i in range(a.shape[0]):
    for j in range(b.shape[0]):
        m[j,i,:,:] = np.matmul(a[i,:,:], b[j,0,:,:])
print('計算時間:{}'.format(time.time()-st))


a: (100, 5, 10)
b: (200, 1, 10, 20)
a * b: (200, 100, 5, 20)
計算時間:0.07759666442871094
計算時間:0.22690081596374512


### 線性代數函數庫 (Torch vs Numpy)

In [14]:
import numpy as np
import torch
a_np = np.array([[6.0, 2.0],
                 [4.0, 5.0]])
a_torch = torch.tensor(a_np)

print(np.linalg.norm(a_np))
print(torch.linalg.norm(a_torch))

print(np.linalg.inv(a_np))
print(torch.linalg.inv(a_torch))

9.0
tensor(9., dtype=torch.float64)
[[ 0.22727273 -0.09090909]
 [-0.18181818  0.27272727]]
tensor([[ 0.2273, -0.0909],
        [-0.1818,  0.2727]], dtype=torch.float64)
