## python操作簡單介紹


Python基本的data structure
* list
* tuple
* dict
* set

使用type()來看變數的型態

## list

在python非常常被拿來使用 <br>
主要是說如果不知道資料要被儲存的長度什麼的可以用list來不斷串接<br>
在語法上用: <br>
- [] <br>
- list()





In [1]:
A=[]
A.append(1)
print('-----')
print(A)
print(type(A))

A.append(2)
A.append(3)
print('-----')
print(A)
print(type(A))

A= list()
for i in range(10):
    A.append(i)
print('-----')
print(A)
print(type(A))

-----
[1]
<class 'list'>
-----
[1, 2, 3]
<class 'list'>
-----
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [2]:
a='I am a.'
b='I am b.'
c='I am c.'
d='I am d.'

A=[a,b,c,d]
print('-----')
print(A)
print(type(A))

A=[a,b,c,d, 123]
print('-----')
print(A)
print(type(A))

-----
['I am a.', 'I am b.', 'I am c.', 'I am d.']
<class 'list'>
-----
['I am a.', 'I am b.', 'I am c.', 'I am d.', 123]
<class 'list'>


### 簡單list操作

有時候我們也可以使用 Python 的內建函數 list() 來創建，例如常被用作產生數列的內建函數 range() 的輸出不會被印出所有的數字，這時可以用轉換為 list 來觀察其中包含的數字。

In [3]:
a=range(10)
print('-----')
print(a)
print(type(a))

a=list(a)
print('-----')
print(a)
print(type(a))

-----
range(0, 10)
<class 'range'>
-----
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [4]:
a='I am a.'
b='I am b.'
c='I am c.'
d='I am d.'
A=[a,b,c,d]
print(A)

print('-----')
print('position 0 of A: \n {}'.format(A[0]))
print('position 1 of A: \n {}'.format(A[1]))
print('position 2 of A: \n {}'.format(A[2]))
print('position 3 of A: \n {}'.format(A[3]))
print('position -1 of A: \n {}'.format(A[-1]))
print('position -2 of A: \n {}'.format(A[-2]))
print('position -3 of A: \n {}'.format(A[-3]))
print('position -4 of A: \n {}'.format(A[-4]))



['I am a.', 'I am b.', 'I am c.', 'I am d.']
-----
position 0 of A: 
 I am a.
position 1 of A: 
 I am b.
position 2 of A: 
 I am c.
position 3 of A: 
 I am d.
position -1 of A: 
 I am d.
position -2 of A: 
 I am c.
position -3 of A: 
 I am b.
position -4 of A: 
 I am a.


In [5]:
A=[1,2,3,4]
print(A)

print('-----')
print('position 0 of A: \n {}'.format(A[0]))
print('position 1 of A: \n {}'.format(A[1]))
print('position 2 of A: \n {}'.format(A[2]))
print('position 3 of A: \n {}'.format(A[3]))

print('position 0:2 of A: \n {}'.format(A[0:2]))
print('position -1:-3 of A: \n {}'.format(A[-3:-1]))


[1, 2, 3, 4]
-----
position 0 of A: 
 1
position 1 of A: 
 2
position 2 of A: 
 3
position 3 of A: 
 4
position 0:2 of A: 
 [1, 2]
position -1:-3 of A: 
 [2, 3]


In [6]:
A =[]
for i in range(10):
    A.append(i)
print(A)
   
A=[i for i in range(10)]
print(A)


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
A =[]
for i in range(10):
    if i% 2 ==0:
        A.append(i)
print(A)
   
A=[i for i in range(10) if i%2==0]
print(A)

[0, 2, 4, 6, 8]
[0, 2, 4, 6, 8]


## tuple

另一常用的資料結構，多數的特性都與 list 相同
在語法上用: <br>
- () <br>
- tuple()<br>


tuple 與 list 最大的差異在於 tuple 是不可變動（immutable）的資料結構，不具備任何包含新增、刪除與排序資料的操作

In [8]:
A=(1,2,3,'AAA')
print(A)
print(type(A))
print(A[2])

(1, 2, 3, 'AAA')
<class 'tuple'>
3


In [9]:
A[2]=3
print(A)

TypeError: 'tuple' object does not support item assignment

## dict

dict 是 dictionary (字典) 的縮寫<br>
dict的資料結構除了儲存資料(values)以外，並利用標籤(keys)來對資料作索引。 <br>
在語法上用: <br>
- {} <br>
- dict() <br>

Example:<br>
老闆手冊<br>
黃小明欠債100元<br>
陳小東欠債200元<br>
張小西欠債100000元<br>

In [10]:
MoneyBook={}
MoneyBook['黃小明']=100
MoneyBook['陳小東']=200
MoneyBook['張小西']=100000
print(MoneyBook)

print(MoneyBook['張小西'])

{'黃小明': 100, '陳小東': 200, '張小西': 100000}
100000


Example:<br>
手冊細部<br>
黃小明欠債100元<br>
陳小東欠債200元<br>
張小西欠債100000元<br>
黃小明欠張小西1000元<br>

In [11]:
MoneyBook_west={}
MoneyBook_west['黃小明']=1000

MoneyBook_Boss={}
MoneyBook_Boss['黃小明']=100
MoneyBook_Boss['陳小東']=200
MoneyBook_Boss['張小西']=[100000, MoneyBook_west]

print(MoneyBook_Boss)

print(MoneyBook_Boss['張小西'])

{'黃小明': 100, '陳小東': 200, '張小西': [100000, {'黃小明': 1000}]}
[100000, {'黃小明': 1000}]


In [12]:
print(MoneyBook_Boss.keys())
print(MoneyBook_Boss.values())
print(MoneyBook_Boss.items())
print(MoneyBook_Boss)

dict_keys(['黃小明', '陳小東', '張小西'])
dict_values([100, 200, [100000, {'黃小明': 1000}]])
dict_items([('黃小明', 100), ('陳小東', 200), ('張小西', [100000, {'黃小明': 1000}])])
{'黃小明': 100, '陳小東': 200, '張小西': [100000, {'黃小明': 1000}]}


In [13]:
for tmp in MoneyBook_Boss:
    print(tmp)
    
print('-'*50)
for key,value in MoneyBook_Boss.items():
    print('{}:{}'.format(key, value))

黃小明
陳小東
張小西
--------------------------------------------------
黃小明:100
陳小東:200
張小西:[100000, {'黃小明': 1000}]


## set

set 我自己也很少用 <br>
set 只會儲存獨一(unique)的資料，若輸入了重複的資訊，則會只記錄一筆。
例如: {a,a,b,b}，只會return a, b
- {} <br>
- set() <br>

In [14]:
A = {"a", "a", "a", "b", "c"}
print(type(A))
print(A)
print('----')
A = set(A)
print(type(A))
print(A)


<class 'set'>
{'b', 'a', 'c'}
----
<class 'set'>
{'b', 'a', 'c'}


In [15]:
A = {1,1,2,2,333333}
print(type(A))
print(A)
print('----')
A = set(A)
print(type(A))
print(A)

<class 'set'>
{1, 2, 333333}
----
<class 'set'>
{1, 2, 333333}


set的結果不能定位置<br>
所以要用for loop來操作

In [16]:
A = {1,1,2,2,333333}
for a in A:
    print(a)
    
A = {"c", "a", "b", "b", "a"}
for a in A:
    print(a)

1
2
333333
c
a
b


## Numpy Brief Introduction

NumPy是Python語言的一個擴充程式庫。<br>
支援高階大量的維度陣列與矩陣運算，此外也針對陣列運算提供大量的數學函式函式庫。<br>

我們稍微介紹numpy的一些簡單運算的介紹<br>




In [17]:
import numpy as np
# Array
A=np.array([1])
print('-----')
print(A)
print(A.shape)

A=np.array([1,2,3])
print('-----')
print(A)
print(A.shape)

## Matrix
A=np.array([[1],[2]])
print('-----')
print(A)
print(A.shape)

A=np.array([[1,2],[3,4]])
print('-----')
print(A)
print(A.shape)


## Tensor
A=np.array([[[1],[2]]])
print('-----')
print(A)
print(A.shape)

A=np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print('-----')
print(A)
print(A.shape)

-----
[1]
(1,)
-----
[1 2 3]
(3,)
-----
[[1]
 [2]]
(2, 1)
-----
[[1 2]
 [3 4]]
(2, 2)
-----
[[[1]
  [2]]]
(1, 2, 1)
-----
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [18]:
a=np.array([1])
b=np.array([2])
print(a+b)

[3]


In [19]:
a=np.array([1,3])
b=np.array([2])
print(a+b)

[3 5]


In [20]:
a=np.array([1,3])
b=np.array([2,3])
print(a+b)

[3 6]


In [21]:
a=np.array([1,3])
b=np.array([2,3])
print(a+b)

[3 6]


In [22]:
a=np.array([[1,2],[3,4]])
b=np.array([[1],[2]])
print('a:\n{}'.format(a))
print('b:\n{}'.format(b))
print('a * b: \n{}'.format(a*b))
print('a dot b:\n{}'.format(np.dot(a,b)))


a:
[[1 2]
 [3 4]]
b:
[[1]
 [2]]
a * b: 
[[1 2]
 [6 8]]
a dot b:
[[ 5]
 [11]]
